### ISSUE TITLE
Quite close but not yet there

### ISSUE THREAD

**Issue by destlaver** [nicopietroni/parafashion#4]
Hi,
one of my job is to make sewing pattern for arbitrary 3d shapes (usualy cartoon heads).
Often I search arxiv papers to see if someone was able to create an algorithm to flatten a 3d model to a 2d pattern as I would manually do myself.
Of all the methods I've seen, yours is the best one so far. 
Sadly It can be used 
professionally yet. 

Here is an example of your algorithm used to flatten a 3D object, the red lines are the cutting lines where I would place the seams manually.
I explicity set the tension to 0 to see all the possibile cutting lines. 
The thing I don't understand is:
I usually put the seams where there is a sudden change in the curvature, aka where there are sharp edges, but your algorithm seams to ignore that in the proximity of the nose, while for the eye and the cheek got it correclty

Last thing, since I'm interested in this project I'm willing to fund something to help you develop this repo. 

![test](https://github.com/nicopietroni/parafashion/assets/56722975/b9d7d4fa-b2c3-4eb2-9aba-164e50dab187)

![WhatsApp Image 2023-09-05 at 15 59 09 - Copia](https://github.com/nicopietroni/parafashion/assets/56722975/d3b837a4-b9c4-4635-b59e-11b813233aea)

**Comment by CorentinDumery** [comment]
Hi @destlaver,

If you press the spacebar and hold, you can input strokes on the UI. These strokes are then used as constraints in the cut generation. Have you tried that? This way you could easily constrain the cuts to be in the locations you mentioned. 

To answer your question: _"I usually put the seams where there is a sudden change in the curvature, aka where there are sharp edges, but your algorithm seams to ignore that in the proximity of the nose, while for the eye and the cheek got it correctly"_
Intuitively, our method adds cuts until the flattening distortion is low enough. If you look at the green patch next to the nose, it is easy to see how it could be flattened without much distortion, it's just like bending a sheet of paper. So it doesn't add a cut there, because the previous cuts are already satisfying.
![image](https://github.com/nicopietroni/parafashion/assets/43251496/beb08e69-92ce-49b7-9647-9d27508976b7)

That being said, it is true that this cutting location would probably be better. If you use the UI to input strokes like I explained earlier, I think you will get the desired results.

Your application is very cool, thanks for sharing it with us :smile: if you don't get the desired results with the constraints, you could also maybe do something like this using UV unwrapping in Blender. But please don't hesitate to contact us again!
