### ISSUE TITLE
Remove unwanted cutting lines

### ISSUE THREAD

**Issue by annie1600** [nicopietroni/parafashion#5]
Hi, 
I am currently conducting research on the cutting lines of 3D scanning garment, and your method is excellent. However, I encountered an issue when using your method for cutting. 
Here is an example of cutting lines generated using your algorithm. Some lines appear rather unusual, such as the cutting line indicated by the green circle. In actual garment production, we do not want such cutting lines. Is there an operational method available to remove the unwanted cutting lines based on the already generated cutting lines?
![1](https://github.com/nicopietroni/parafashion/assets/153593254/a133c823-f860-4e7f-9d54-35e8cfd9b1d8)

**Comment by CorentinDumery** [comment]
Hi @annie1600, yes those results are not very good, I think it's because the input mesh has some pretty strange folds and wrinkles, which may not be physically accurate and make the garment highly non-developable. The cuts in the green circle are here to accommodate for the weird fold in the middle/bottom.

There is no such option in the UI, but it would be pretty straightforward to import the patches in Blender and merge the ones you'd like, effectively removing the cut. Would that be an option for you?

**Comment by CorentinDumery** [comment]
I hope that helped, I'll close the issue now.

**Comment by CorentinDumery** [comment]
I hope that helped, I'll close the issue now.
